name: Build GitHub Pages (mkdocs)

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  main:
    name: Build GitHub Pages with mkdocs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true

      - uses: actions/setup-python@v2
        with:
          python-version: '3.8.5'

      - name: Install mkdocs
        run: |
          mkdir python-mkdocs-venv;
          python -m venv python-mkdocs-venv;
          source python-mkdocs-venv/bin/activate;
          pip install -U mkdocs;

      - name: Build the GitHub pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "GitHub Action"

          git lfs fetch --all
          git lfs ls-files -n | xargs git lfs untrack
          git rm -f .gitattributes
          git add --renormalize .
          git lfs uninstall
          git commit -m 'Commit LFS files'

          source python-mkdocs-venv/bin/activate;
          cd documentation;
          mkdocs gh-deploy --force;
