name: Release Build

on:
  push:
    branches:
      - 'release/*'

jobs:
  main:
    name: Build the release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Define the version
        id: version
        run: |
          VERSION=$(echo "${{ github.ref }}" | python -c 'import sys; a=sys.stdin.read().strip(); print(a.split("/")[-1])')
          echo "##[set-output name=version;]$VERSION"

      - name: Prepare the filesystem structure
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "GitHub Action"

          git lfs fetch --all
          git lfs ls-files -n | xargs git lfs untrack
          git rm -f .gitattributes
          git lfs uninstall

          git add --renormalize .

          mv ./addon/* .;
          rm -rf README.md addon;

          git add .

          git commit -m 'Release ${{ steps.version.outputs.version }}';
          git tag ${{ steps.version.outputs.version }};
          git push origin ${{ github.ref }} --tags

      - name: Create Release
        id: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.version.outputs.version }}
          release_name: Release ${{ steps.version.outputs.version }}

      - name: Package the release
        id: package-the-release
        run: |
          rm -rf .git .gitignore .gitattributes .github .flake8
          mkdir ../release
          cp -r . ../release/chiro_ue4
          cd ../release
          zip -9 -r "chiro-ue4-${{ steps.version.outputs.version }}.zip" chiro_ue4

      - name: Upload the release
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: "${{ steps.create-release.outputs.upload_url }}"
          asset_path: "../release/chiro-ue4-${{ steps.version.outputs.version }}.zip"
          asset_name: "chiro-ue4-${{ steps.version.outputs.version }}.zip"
          asset_content_type: application/zip
